import type { Metadata } from "next";
import { Roboto, Poppins } from "next/font/google";
import "../../styles/globals.scss";
import Header from "./(componentes)/ui/header";
import Footer from "./(componentes)/ui/footer";
import styles from './page.module.scss'
import 'leaflet/dist/leaflet.css'

const roboto = Roboto({
  weight: ['300', '500', '600', '700'],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['300', '400', '500', '600'],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cameras C-Com FM - 102,7 Além Paraiba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${roboto.variable} ${poppins.variable} antialiased`}
      >
        <Header />
        <main className={styles.mainContainer}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
